/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUnityRouteImport } from './routes/api/unity'
import { Route as ApiCapeRouteImport } from './routes/api/cape'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnityRoute = ApiUnityRouteImport.update({
  id: '/api/unity',
  path: '/api/unity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapeRoute = ApiCapeRouteImport.update({
  id: '/api/cape',
  path: '/api/cape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/launch': typeof LaunchRoute
  '/register': typeof RegisterRoute
  '/score': typeof ScoreRoute
  '/tutorial': typeof TutorialRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/launch': typeof LaunchRoute
  '/register': typeof RegisterRoute
  '/score': typeof ScoreRoute
  '/tutorial': typeof TutorialRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/launch': typeof LaunchRoute
  '/register': typeof RegisterRoute
  '/score': typeof ScoreRoute
  '/tutorial': typeof TutorialRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/launch'
    | '/register'
    | '/score'
    | '/tutorial'
    | '/api/cape'
    | '/api/unity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/launch'
    | '/register'
    | '/score'
    | '/tutorial'
    | '/api/cape'
    | '/api/unity'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/launch'
    | '/register'
    | '/score'
    | '/tutorial'
    | '/api/cape'
    | '/api/unity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  LaunchRoute: typeof LaunchRoute
  RegisterRoute: typeof RegisterRoute
  ScoreRoute: typeof ScoreRoute
  TutorialRoute: typeof TutorialRoute
  ApiCapeRoute: typeof ApiCapeRoute
  ApiUnityRoute: typeof ApiUnityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity': {
      id: '/api/unity'
      path: '/api/unity'
      fullPath: '/api/unity'
      preLoaderRoute: typeof ApiUnityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cape': {
      id: '/api/cape'
      path: '/api/cape'
      fullPath: '/api/cape'
      preLoaderRoute: typeof ApiCapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  LaunchRoute: LaunchRoute,
  RegisterRoute: RegisterRoute,
  ScoreRoute: ScoreRoute,
  TutorialRoute: TutorialRoute,
  ApiCapeRoute: ApiCapeRoute,
  ApiUnityRoute: ApiUnityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
