import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildBlockDrivenLanding, buildBlockDrivenLoading, buildBlockDrivenVideo } from '../page-builder.js';

describe('buildBlockDrivenLanding', () => {
  const minimalBlocks = [
    { name: 'background', settings: { kind: 'image' } },
    { name: 'header-chrome', settings: { leftSlot: 'menu', rightSlot: 'none' } },
    { name: 'brand-chip', settings: { size: 'md' } },
    { name: 'title-block', settings: { showKicker: false, showSubtitle: false } },
    { name: 'cta-group', settings: { count: 1, buttons: [{ variant: 'primary', exit: 'game' }] } },
  ];

  it('returns a non-empty TSX string', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.equal(typeof out, 'string');
    assert.ok(out.length > 0);
  });

  it('emits an import for every block in the list', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /import \{ Background \}/);
    assert.match(out, /import \{ HeaderChrome \}/);
    assert.match(out, /import \{ BrandChip \}/);
    assert.match(out, /import \{ TitleBlock \}/);
    assert.match(out, /import \{ CtaGroup \}/);
  });

  it('emits a "Generated by campaign-scaffolder" header comment', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /^\/\/ Generated by campaign-scaffolder/m);
  });

  it('wires CtaGroup with the requested button count', () => {
    const blocks = [
      ...minimalBlocks.slice(0, 4),
      { name: 'cta-group', settings: { count: 2, buttons: [
        { variant: 'primary', exit: 'game' },
        { variant: 'secondary', exit: 'leaderboard' },
      ]}},
    ];
    const out = buildBlockDrivenLanding(blocks);
    assert.match(out, /router\.push\(['"]\/gameplay['"]\)/);
    assert.match(out, /router\.push\(['"]\/leaderboard['"]\)/);
  });

  it('throws when a required block (background or title-block) is missing', () => {
    const noBg = minimalBlocks.filter((b) => b.name !== 'background');
    assert.throws(() => buildBlockDrivenLanding(noBg), /background/);
  });

  it('emits a "use client" directive at the top of the output', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /^'use client';/);
  });

  it('keeps the router available for chrome/navigation even without cta-group', () => {
    const blocksWithoutCta = minimalBlocks.filter((b) => b.name !== 'cta-group');
    const out = buildBlockDrivenLanding(blocksWithoutCta);
    assert.match(out, /useRouter/);
  });

  it('emits useRouter import & binding when cta-group IS present', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /import \{ useRouter \} from 'next\/navigation';/);
    assert.match(out, /const router = useRouter\(\);/);
  });

  it('omits useRouter when no enabled block navigates', () => {
    const out = buildBlockDrivenLoading([
      { name: 'background', settings: { kind: 'image' } },
      { name: 'centered-art', settings: { size: 'md' } },
      { name: 'brand-chip', settings: { size: 'md' } },
      { name: 'tagline', settings: {} },
      { name: 'loading-indicator', settings: { kind: 'ring' } },
    ]);
    assert.doesNotMatch(out, /useRouter/);
  });

  it('does not auto-advance wait-for-engine video blocks', () => {
    const out = buildBlockDrivenVideo([
      { name: 'background', settings: { kind: 'solid' } },
      { name: 'header-chrome', settings: { leftSlot: 'none', rightSlot: 'none' } },
      { name: 'video-player', settings: { muted: true, loop: true, onEnd: 'wait-for-engine' } },
      { name: 'fallback-indicator', settings: {} },
    ]);
    assert.doesNotMatch(out, /onEnded=\{\(\) => router\.push/);
    assert.doesNotMatch(out, /useRouter/);
  });
});
