import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildBlockDrivenLanding } from '../page-builder.js';

describe('buildBlockDrivenLanding', () => {
  const minimalBlocks = [
    { name: 'background', settings: { kind: 'image' } },
    { name: 'header-chrome', settings: { leftSlot: 'menu', rightSlot: 'none' } },
    { name: 'brand-chip', settings: { size: 'md' } },
    { name: 'title-block', settings: { showKicker: false, showSubtitle: false } },
    { name: 'cta-group', settings: { count: 1, buttons: [{ variant: 'primary', exit: 'game' }] } },
  ];

  it('returns a non-empty TSX string', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.equal(typeof out, 'string');
    assert.ok(out.length > 0);
  });

  it('emits an import for every block in the list', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /import \{ Background \}/);
    assert.match(out, /import \{ HeaderChrome \}/);
    assert.match(out, /import \{ BrandChip \}/);
    assert.match(out, /import \{ TitleBlock \}/);
    assert.match(out, /import \{ CtaGroup \}/);
  });

  it('emits a "Generated by campaign-scaffolder" header comment', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /^\/\/ Generated by campaign-scaffolder/m);
  });

  it('wires CtaGroup with the requested button count', () => {
    const blocks = [
      ...minimalBlocks.slice(0, 4),
      { name: 'cta-group', settings: { count: 2, buttons: [
        { variant: 'primary', exit: 'game' },
        { variant: 'secondary', exit: 'leaderboard' },
      ]}},
    ];
    const out = buildBlockDrivenLanding(blocks);
    assert.match(out, /router\.push\(['"]\/game['"]\)/);
    assert.match(out, /router\.push\(['"]\/leaderboard['"]\)/);
  });

  it('throws when a required block (background or title-block) is missing', () => {
    const noBg = minimalBlocks.filter((b) => b.name !== 'background');
    assert.throws(() => buildBlockDrivenLanding(noBg), /background/);
  });
});
