import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildBlockDrivenLanding, buildBlockDrivenLoading, buildBlockDrivenPage, buildBlockDrivenVideo } from '../page-builder.js';

describe('buildBlockDrivenLanding', () => {
  const minimalBlocks = [
    { name: 'background', settings: { kind: 'image' } },
    { name: 'header-chrome', settings: { leftSlot: 'menu', rightSlot: 'none' } },
    { name: 'brand-chip', settings: { size: 'md' } },
    { name: 'title-block', settings: { showKicker: false, showSubtitle: false } },
    { name: 'cta-group', settings: { count: 1, buttons: [{ variant: 'primary', exit: 'game' }] } },
  ];

  it('returns a non-empty TSX string', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.equal(typeof out, 'string');
    assert.ok(out.length > 0);
  });

  it('emits an import for every block in the list', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /import \{ Background \}/);
    assert.match(out, /import \{ HeaderChrome \}/);
    assert.match(out, /import \{ BrandChip \}/);
    assert.match(out, /import \{ TitleBlock \}/);
    assert.match(out, /import \{ CtaGroup \}/);
  });

  it('emits a "Generated by campaign-scaffolder" header comment', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /^\/\/ Generated by campaign-scaffolder/m);
  });

  it('wires one CtaGroup button per entry in `buttons` (no count needed)', () => {
    const blocks = [
      ...minimalBlocks.slice(0, 4),
      { name: 'cta-group', settings: { buttons: [
        { variant: 'primary', exit: 'game' },
        { variant: 'secondary', exit: 'leaderboard' },
      ]}},
    ];
    const out = buildBlockDrivenLanding(blocks);
    assert.match(out, /router\.push\(['"]\/gameplay['"]\)/);
    assert.match(out, /router\.push\(['"]\/leaderboard['"]\)/);
    assert.match(out, /variant: 'primary'/);
    assert.match(out, /variant: 'secondary'/);
  });

  it('still honors a legacy `count` as a cap on the button list', () => {
    const blocks = [
      ...minimalBlocks.slice(0, 4),
      { name: 'cta-group', settings: { count: 1, buttons: [
        { variant: 'primary', exit: 'game' },
        { variant: 'secondary', exit: 'leaderboard' },
      ]}},
    ];
    const out = buildBlockDrivenLanding(blocks);
    assert.match(out, /router\.push\(['"]\/gameplay['"]\)/);
    assert.doesNotMatch(out, /router\.push\(['"]\/leaderboard['"]\)/);
  });

  it('throws when a required block (background or title-block) is missing', () => {
    const noBg = minimalBlocks.filter((b) => b.name !== 'background');
    assert.throws(() => buildBlockDrivenLanding(noBg), /background/);
  });

  it('emits a "use client" directive at the top of the output', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /^'use client';/);
  });

  it('keeps the router available for chrome/navigation even without cta-group', () => {
    const blocksWithoutCta = minimalBlocks.filter((b) => b.name !== 'cta-group');
    const out = buildBlockDrivenLanding(blocksWithoutCta);
    assert.match(out, /useRouter/);
  });

  it('emits useRouter import & binding when cta-group IS present', () => {
    const out = buildBlockDrivenLanding(minimalBlocks);
    assert.match(out, /import \{ useRouter \} from 'next\/navigation';/);
    assert.match(out, /const router = useRouter\(\);/);
  });

  it('omits useRouter when no enabled block navigates', () => {
    const out = buildBlockDrivenLoading([
      { name: 'background', settings: { kind: 'image' } },
      { name: 'centered-art', settings: { size: 'md' } },
      { name: 'brand-chip', settings: { size: 'md' } },
      { name: 'tagline', settings: {} },
      { name: 'loading-indicator', settings: { kind: 'ring' } },
    ]);
    assert.doesNotMatch(out, /useRouter/);
  });

  it('does not auto-advance wait-for-engine video blocks', () => {
    const out = buildBlockDrivenVideo([
      { name: 'background', settings: { kind: 'solid' } },
      { name: 'header-chrome', settings: { leftSlot: 'none', rightSlot: 'none' } },
      { name: 'video-player', settings: { muted: true, loop: true, onEnd: 'wait-for-engine' } },
      { name: 'fallback-indicator', settings: {} },
    ]);
    assert.doesNotMatch(out, /onEnded=\{\(\) => router\.push/);
    assert.doesNotMatch(out, /useRouter/);
  });

  it('uses the current loading video fallback asset', () => {
    const out = buildBlockDrivenVideo([
      { name: 'background', settings: { kind: 'solid' } },
      { name: 'header-chrome', settings: { leftSlot: 'none', rightSlot: 'none' } },
      { name: 'video-player', settings: { muted: true, loop: true, onEnd: 'wait-for-engine' } },
      { name: 'fallback-indicator', settings: {} },
    ]);
    assert.match(out, /cape\.video \?\? '\/assets\/livewall-loading\.mp4'/);
    assert.doesNotMatch(out, /livewall-intro-loadingvid/);
  });

  it('does not leak generic leaderboard placeholders', () => {
    const out = buildBlockDrivenPage('leaderboard', 'leaderboard', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'title-block', settings: { showKicker: true, showSubtitle: true } },
      { name: 'rank-list', settings: { rows: 4 } },
      { name: 'personal-best-row', settings: {} },
    ]);

    assert.match(out, /cape\.title && cape\.title !== 'Title' \? cape\.title : "Leaderboard"/);
    assert.match(out, /rows=\{\(cape\.rankings \?\? \[\]\)\.slice\(0, 4\)\}/);
    assert.match(out, /rank=\{cape\.personalRank\} score=\{cape\.personalBest\}/);
    assert.doesNotMatch(out, /title=\{cape\.title \?\? 'Title'\}/);
    assert.doesNotMatch(out, /personalRank \?\? 0/);
    assert.doesNotMatch(out, /personalBest \?\? 0/);
  });

  it('reads result score from GameContext', () => {
    const out = buildBlockDrivenPage('result', 'result', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'title-block', settings: { showKicker: false, showSubtitle: true } },
      { name: 'score-readout', settings: { showHighScore: true } },
      { name: 'cta-group', settings: { buttons: [{ variant: 'primary', exit: 'landing' }] } },
    ]);

    assert.match(out, /import \{ useGameContext \} from '@hooks\/useGameContext';/);
    assert.match(out, /const \{ score, highscore \} = useGameContext\(\);/);
    assert.match(out, /<ScoreReadout score=\{score \?\? cape\.score \?\? 0\}/);
    assert.match(out, /highScore=\{highscore \|\| cape\.highScore\}/);
  });

  it('marks registration locally and skips the register page after submit', () => {
    const out = buildBlockDrivenPage('register', 'register', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'card-wrapper', settings: { style: 'card' } },
      { name: 'field-set', settings: { fields: ['firstName', 'email'] } },
      { name: 'opt-in-list', settings: { optIns: ['terms'] } },
      { name: 'cta-group', settings: { buttons: [{ variant: 'primary', exit: 'voucher' }] } },
    ], { capeId: '63633', pages: ['register', 'voucher'], routeMap: { voucher: '/voucher' } });

    assert.match(out, /const REGISTERED_KEY = "lw_registered_63633";/);
    assert.match(out, /if \(isRegistered\(\)\) router\.replace\("\/voucher"\);/);
    assert.match(out, /const finishRegister = \(\) => \{/);
    assert.match(out, /markRegistered\(\);/);
    assert.match(out, /router\.push\("\/voucher"\);/);
    assert.match(out, /onClick: \(\) => finishRegister\(\)/);
  });

  it('shows leaderboard result action after registration is completed', () => {
    const out = buildBlockDrivenPage('result', 'result', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'title-block', settings: { showKicker: false, showSubtitle: true } },
      { name: 'score-readout', settings: { showHighScore: true } },
      { name: 'cta-group', settings: {
        buttons: [{ variant: 'primary', exit: 'register' }],
        registeredButtons: [
          { variant: 'secondary', exit: 'landing' },
          { variant: 'tertiary', exit: 'leaderboard' },
          { variant: 'primary', exit: 'game' },
        ],
      } },
    ], {
      capeId: '63633',
      pages: ['landing', 'result', 'register', 'leaderboard', 'game'],
      routeMap: { landing: '/landing', register: '/register', leaderboard: '/leaderboard', game: '/gameplay' },
    });

    assert.match(out, /hasRegistered \? \[\{ label: cape\.registeredCta\?\.\[0\]\?\.label \|\| cape\.registeredCta\?\.\[0\] \|\| "Home"/);
    assert.match(out, /\{ label: cape\.registeredCta\?\.\[1\]\?\.label \|\| cape\.registeredCta\?\.\[1\] \|\| "Leaderboard", variant: 'tertiary', onClick: \(\) => router\.push\("\/leaderboard"\) \}/);
    assert.match(out, /\{ label: cape\.registeredCta\?\.\[2\]\?\.label \|\| cape\.registeredCta\?\.\[2\] \|\| "Play again", variant: 'primary', onClick: \(\) => router\.push\("\/gameplay"\) \}/);
  });

  it('does not skip register when the flow rule says always show', () => {
    const out = buildBlockDrivenPage('register', 'register', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'card-wrapper', settings: { style: 'card' } },
      { name: 'field-set', settings: { fields: ['firstName', 'email'] } },
      { name: 'opt-in-list', settings: { optIns: ['terms'] } },
      { name: 'cta-group', settings: { buttons: [{ variant: 'primary', exit: 'voucher' }] } },
    ], {
      capeId: '63633',
      pages: ['register', 'voucher'],
      routeMap: { voucher: '/voucher' },
      flowRules: { register: { mode: 'always' } },
    });

    assert.doesNotMatch(out, /REGISTERED_KEY/);
    assert.doesNotMatch(out, /finishRegister/);
    assert.match(out, /router\.push\("\/voucher"\)/);
  });

  it('does not skip tutorial when the flow rule says always show', () => {
    const out = buildBlockDrivenPage('landing', 'landing', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'title-block', settings: { showSubtitle: true } },
      { name: 'cta-group', settings: { buttons: [{ variant: 'primary', exit: 'tutorial' }] } },
    ], {
      capeId: '63633',
      pages: ['landing', 'tutorial', 'loading-video', 'game'],
      routeMap: { tutorial: '/tutorial', 'loading-video': '/loading-video', game: '/gameplay' },
      flowRules: { tutorial: { mode: 'always' } },
    });

    assert.doesNotMatch(out, /ONBOARDING_KEY/);
    assert.doesNotMatch(out, /isOnboardingDone/);
    assert.match(out, /router\.push\("\/tutorial"\)/);
  });

  it('does not rewrite a landing CTA that explicitly targets game', () => {
    const out = buildBlockDrivenPage('landing', 'landing', [
      { name: 'background', settings: { kind: 'image' } },
      { name: 'title-block', settings: { showSubtitle: true } },
      { name: 'cta-group', settings: { buttons: [{ variant: 'primary', exit: 'game' }] } },
    ], {
      capeId: '63633',
      pages: ['landing', 'tutorial', 'loading-video', 'game'],
      routeMap: { tutorial: '/tutorial', 'loading-video': '/loading-video', game: '/gameplay' },
      flowRules: { tutorial: { mode: 'once-per-browser' } },
    });

    assert.doesNotMatch(out, /isOnboardingDone/);
    assert.match(out, /router\.push\("\/gameplay"\)/);
  });
});
