// ─────────────────────────────────────────────────────────────────────────────
// React → Unity  (what we send)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Core payload sent to Unity via WebService.SetData.
 * `translations` is a flat key-value map flattened from CAPE copy.
 * Extend this interface per-campaign for game-specific data (teams, config, etc.)
 */
export interface IUnityInput {
  environment: 'local' | 'acceptance' | 'production';
  muted: boolean;
  /** Flat key-value copy map. Keys are camelCase paths, e.g. "gamePlayTitle" */
  translations: IUnityTranslations;
  /** Whether to play the tutorial on this boot */
  playTutorial?: boolean;
  /** Set to true on local builds to skip real API calls inside Unity */
  useMockAPI?: boolean;
}

/** Flat translation map sent to Unity — generated by buildUnityTranslations() */
export type IUnityTranslations = Record<string, string>;

/** Payload sent to Unity via WebService.SetScene to select + preload a scene */
export interface IUnitySceneLoad {
  sceneKey: string;
  skipPreload?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Unity → React  (what we receive)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Emitted by Unity on the 'end' event.
 * Extend per-campaign for extra fields (goalsScored, filledGlasses, etc.)
 */
export interface IGameResult {
  score?: number;
  playTime?: number;
  [key: string]: unknown;
}

/**
 * Unity requests a navigation action.
 * Emitted on the 'navigation' event.
 */
export interface IUnityNavigation {
  type: UnityNavigationType;
  /** Internal route path or external URL */
  target?: string;
}

export enum UnityNavigationType {
  INTERNAL_URL = 0,
  EXTERNAL_URL = 1,
  TERMS = 2,
}

/**
 * Unity fires an analytics event.
 * Emitted on the 'tracking' event.
 */
export interface IUnityTracking {
  type: UnityTrackingType;
  name: string;
  data?: Record<string, unknown>;
}

export enum UnityTrackingType {
  VIEW = 0,
  EVENT = 1,
}

/**
 * Unity asks the frontend to make an HTTP request on its behalf (CORS proxy).
 * Emitted on the 'apiRequest' event.
 * Respond by calling sendMessage('APIService', 'ProcessResponse', JSON.stringify(response))
 */
export interface IUnityApiRequest {
  /** Correlation ID — must be echoed in the response */
  uuid: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  data?: object;
}

export interface IUnityApiResponse<T = unknown> {
  success: boolean;
  uuid: string;
  data: T;
}

// ─────────────────────────────────────────────────────────────────────────────
// Adapter contract
// ─────────────────────────────────────────────────────────────────────────────

export type GameBridgeEventName =
  | 'loading'
  | 'ready'
  | 'sceneLoaded'
  | 'addressableLoaded'
  | 'start'
  | 'end'
  | 'navigation'
  | 'tracking'
  | 'apiRequest'
  | 'tutorialPlayed'
  | 'muted'
  | (string & {});

export type GameBridgeEventCallback<T = unknown> = (data: T) => void;

export interface IGameBridgeAdapter {
  /** Push game data to the engine. Stored and replayed on each loadScene() call. */
  setData(input: IUnityInput): void;
  /** Set target scene key — triggers preload if already in controller scene */
  setTargetScene(sceneKey: string): void;
  /** Raw engine message dispatch */
  sendMessage(objectName: string, methodName: string, data?: string): void;
  /** Subscribe to an engine event */
  on<T = unknown>(event: GameBridgeEventName, cb: GameBridgeEventCallback<T>): void;
  /** Unsubscribe */
  off<T = unknown>(event: GameBridgeEventName, cb: GameBridgeEventCallback<T>): void;
  /** Wait for a specific event, resolving when it fires */
  waitFor<T = unknown>(event: GameBridgeEventName, timeoutMs?: number): Promise<T>;
  /** Full boot: init → preload → load → (caller calls startGame) */
  fullBoot(): Promise<void>;
  /** Trigger the StartGame message — call after fullBoot resolves */
  startGame(): void;
  /** Tear down all listeners and free resources */
  destroy(): void;
}
