/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUnityRouteImport } from './routes/api/unity'
import { Route as ApiCapeRouteImport } from './routes/api/cape'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnityRoute = ApiUnityRouteImport.update({
  id: '/api/unity',
  path: '/api/unity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapeRoute = ApiCapeRouteImport.update({
  id: '/api/cape',
  path: '/api/cape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/landing': typeof LandingRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/tutorial': typeof TutorialRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/landing': typeof LandingRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/tutorial': typeof TutorialRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/landing': typeof LandingRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/tutorial': typeof TutorialRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/landing'
    | '/register'
    | '/result'
    | '/tutorial'
    | '/api/cape'
    | '/api/unity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/landing'
    | '/register'
    | '/result'
    | '/tutorial'
    | '/api/cape'
    | '/api/unity'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/landing'
    | '/register'
    | '/result'
    | '/tutorial'
    | '/api/cape'
    | '/api/unity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  LandingRoute: typeof LandingRoute
  RegisterRoute: typeof RegisterRoute
  ResultRoute: typeof ResultRoute
  TutorialRoute: typeof TutorialRoute
  ApiCapeRoute: typeof ApiCapeRoute
  ApiUnityRoute: typeof ApiUnityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity': {
      id: '/api/unity'
      path: '/api/unity'
      fullPath: '/api/unity'
      preLoaderRoute: typeof ApiUnityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cape': {
      id: '/api/cape'
      path: '/api/cape'
      fullPath: '/api/cape'
      preLoaderRoute: typeof ApiCapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  LandingRoute: LandingRoute,
  RegisterRoute: RegisterRoute,
  ResultRoute: ResultRoute,
  TutorialRoute: TutorialRoute,
  ApiCapeRoute: ApiCapeRoute,
  ApiUnityRoute: ApiUnityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
