/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by campaign-scaffolder.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as GameRouteImport } from './routes/game'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ApiCapeRouteImport } from './routes/api/cape'
import { Route as ApiUnityRouteImport } from './routes/api/unity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapeRoute = ApiCapeRouteImport.update({
  id: '/api/cape',
  path: '/api/cape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnityRoute = ApiUnityRouteImport.update({
  id: '/api/unity',
  path: '/api/unity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/tutorial': typeof TutorialRoute
  '/game': typeof GameRoute
  '/result': typeof ResultRoute
  '/register': typeof RegisterRoute
  '/leaderboard': typeof LeaderboardRoute
  '/menu': typeof MenuRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/tutorial': typeof TutorialRoute
  '/game': typeof GameRoute
  '/result': typeof ResultRoute
  '/register': typeof RegisterRoute
  '/leaderboard': typeof LeaderboardRoute
  '/menu': typeof MenuRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/tutorial': typeof TutorialRoute
  '/game': typeof GameRoute
  '/result': typeof ResultRoute
  '/register': typeof RegisterRoute
  '/leaderboard': typeof LeaderboardRoute
  '/menu': typeof MenuRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/unity': typeof ApiUnityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/tutorial'
    | '/game'
    | '/result'
    | '/register'
    | '/leaderboard'
    | '/menu'
    | '/api/cape'
    | '/api/unity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/tutorial'
    | '/game'
    | '/result'
    | '/register'
    | '/leaderboard'
    | '/menu'
    | '/api/cape'
    | '/api/unity'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/tutorial'
    | '/game'
    | '/result'
    | '/register'
    | '/leaderboard'
    | '/menu'
    | '/api/cape'
    | '/api/unity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  TutorialRoute: typeof TutorialRoute
  GameRoute: typeof GameRoute
  ResultRoute: typeof ResultRoute
  RegisterRoute: typeof RegisterRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MenuRoute: typeof MenuRoute
  ApiCapeRoute: typeof ApiCapeRoute
  ApiUnityRoute: typeof ApiUnityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cape': {
      id: '/api/cape'
      path: '/api/cape'
      fullPath: '/api/cape'
      preLoaderRoute: typeof ApiCapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity': {
      id: '/api/unity'
      path: '/api/unity'
      fullPath: '/api/unity'
      preLoaderRoute: typeof ApiUnityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  TutorialRoute: TutorialRoute,
  GameRoute: GameRoute,
  ResultRoute: ResultRoute,
  RegisterRoute: RegisterRoute,
  LeaderboardRoute: LeaderboardRoute,
  MenuRoute: MenuRoute,
  ApiCapeRoute: ApiCapeRoute,
  ApiUnityRoute: ApiUnityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
